import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

//eslint-disable-next-line import/no-unused-modules
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//eslint-disable-next-line import/no-unused-modules
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
